name: Build and Push LangFlow Images to GHCR

on:
  push:
    branches:
      - main  # Change this if needed
  workflow_dispatch:  # Allow manual runs

jobs:
  build-and-push-langflow:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        run: |
          echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and Push Langflow (Full)
        run: |
          docker build -t ghcr.io/${{ github.actor }}/shadowforge:latest -f docker/build_and_push.Dockerfile .
          docker push ghcr.io/${{ github.actor }}/shadowforge:latest

  build-and-push-backend:
    needs: build-and-push-langflow  # Wait for the full Langflow image to be built
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        run: |
          echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and Push Backend-Only Image
        run: |
          docker build --build-arg LANGFLOW_IMAGE=ghcr.io/${{ github.actor }}/shadowforge:latest \
            -t ghcr.io/${{ github.actor }}/shadowforge-backend:latest -f docker/build_and_push_backend.Dockerfile .
          docker push ghcr.io/${{ github.actor }}/shadowforge-backend:latest

  build-and-push-frontend:
    needs: build-and-push-langflow  # Frontend depends on the full Langflow image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        run: |
          echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and Push Frontend Image
        run: |
          docker build -t ghcr.io/${{ github.actor }}/shadowforge-frontend:latest -f docker/frontend/build_and_push_frontend.Dockerfile .
          docker push ghcr.io/${{ github.actor }}/shadowforge-frontend:latest