name: Publish LangFlow Development to ghcr.io

on:
  workflow_dispatch:  # Manual trigger only

jobs:
  push-langflow:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Make build script executable
        run: chmod +x docker/build-langflow-dev.sh

      - name: Run LangFlow Build Script
        run: docker/build-langflow-dev.sh

      - name: Tag LangFlow Image
        run: |
          REPO_NAME=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')  # Convert repo name to lowercase
          docker tag dev-langflow ghcr.io/$REPO_NAME/shadowforge:development

      - name: Push LangFlow Image to GHCR
        run: |
          REPO_NAME=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          docker push ghcr.io/$REPO_NAME/shadowforge:development